### ISSUE TITLE
unittest.RunCodeGen.TestSimpleSlect() may fail because can't find csc.exe

### ISSUE THREAD

**Issue by zhouqingqing** [zhouqingqing/qpmodel#99]
csc.exe is the roslyn compiler and error is "Could not find a part of the path … bin\roslyn\csc.exe".

We can workaround the issue by copy roslyn package in debug folder once. But good to find a complete solution - it could be somewhere in path setting.

**Comment by arzuschen** [comment]
The solution is to install Microsoft.CodeDom.Providers.DotNetCompilerPlatform to the project for unittest.

One way is through NuGet Package Manager:
In Solution Explorer, right click the "test" project to find "Manage NuGet Packages". In the manager specifically for "test", you can search for Microsoft.CodeDom.Providers.DotNetCompilerPlatform and install the package.

The other way is through NuGet Console. This command should work as the same as the previous way:
`PM> Install-Package Microsoft.CodeDom.Providers.DotNetCompilerPlatform -ProjectName test`

Updating the package is not working because there was no Microsoft.CodeDom.Providers.DotNetCompilerPlatform package within the project at the point.

**Comment by zhouqingqing** [comment]
fixed
